import xlsx from 'xlsx';
import { resolveStateCode, parseInvoiceDate } from './commonSchema.js';
import { toPaise } from '../engine/money.js';
import { MARKETPLACE_ETIN } from '../config/constants.js';

// Case-insensitive header matching helper
function getVal(row, candidates, fallback = '') {
  const keys = Object.keys(row);
  for (const candidate of candidates) {
    const cleanCand = candidate.toLowerCase().replace(/[^a-z0-9]/g, '');
    for (const k of keys) {
      const cleanKey = k.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (cleanKey === cleanCand && row[k] !== undefined && row[k] !== null && row[k] !== '') {
        return row[k];
      }
    }
  }
  return fallback;
}

/**
 * Flipkart XLSX files generated by Flipkart export service often have a corrupted
 * `!ref` header tag (e.g. 'A1:BH1') that only spans row 1.
 * SheetJS uses `!ref` to bound `sheet_to_json`. Recalculating `!ref` from cell keys
 * ensures all rows are read.
 */
function ensureSheetRange(ws) {
  if (!ws) return;
  let minRow = Infinity, maxRow = 0, minCol = Infinity, maxCol = 0;
  Object.keys(ws).forEach(key => {
    if (key[0] === '!') return;
    const cell = xlsx.utils.decode_cell(key);
    if (cell.r < minRow) minRow = cell.r;
    if (cell.r > maxRow) maxRow = cell.r;
    if (cell.c < minCol) minCol = cell.c;
    if (cell.c > maxCol) maxCol = cell.c;
  });
  if (minRow !== Infinity) {
    ws['!ref'] = xlsx.utils.encode_range({ s: { r: minRow, c: minCol }, e: { r: maxRow, c: maxCol } });
  }
}

/**
 * Parses Flipkart GST / Sales Report + Cash Back Report in XLSX format
 */
export async function parseFlipkartReport(filePath, sellerStateCode) {
  const workbook = xlsx.readFile(filePath);
  
  // Explicitly target data sheet names: 'Sales Report' and 'Cash Back Report'. Never parse 'Help'.
  const targetSheetNames = workbook.SheetNames.filter(name => {
    const lower = name.toLowerCase();
    return !lower.includes('help') && (
      lower.includes('sale') || lower.includes('cash') || lower.includes('back') || lower.includes('tax')
    );
  });

  // Fallback if sheet names differ unexpectedly but avoid 'Help'
  if (targetSheetNames.length === 0) {
    const nonHelp = workbook.SheetNames.filter(n => !n.toLowerCase().includes('help'));
    if (nonHelp.length > 0) targetSheetNames.push(nonHelp[0]);
    else if (workbook.SheetNames.length > 0) targetSheetNames.push(workbook.SheetNames[0]);
  }

  const orderLines = [];
  const errors = [];
  const warnings = [];

  for (const sheetName of targetSheetNames) {
    const worksheet = workbook.Sheets[sheetName];
    if (!worksheet) continue;

    // Fix corrupted !ref range boundary if present
    ensureSheetRange(worksheet);

    const rawRows = xlsx.utils.sheet_to_json(worksheet, { defval: '' });
    const isCashBackSheet = sheetName.toLowerCase().includes('cash') || sheetName.toLowerCase().includes('back');

    let rowIndex = 1;

    for (const row of rawRows) {
      rowIndex++;

      const invoiceNumber = String(getVal(row, [
        'Buyer Invoice ID', 'Credit Note ID/ Debit Note ID', 'Credit Note ID', 'Debit Note ID',
        'Invoice No', 'Invoice Number', 'Invoice ID', 'Tax Invoice No', 'Invoice Details'
      ])).trim();

      const orderId = String(getVal(row, ['Order ID', 'Order Id', 'Order Item ID', 'Flipkart Order ID', 'Item ID'])).trim();

      if (!invoiceNumber && !orderId) {
        continue;
      }

      const invoiceDateRaw = getVal(row, ['Buyer Invoice Date', 'Invoice Date', 'Order Date', 'Event Date', 'Date']);
      const invoiceDate = parseInvoiceDate(invoiceDateRaw);

      const eventTypeRaw = String(getVal(row, [
        'Event Type', 'Document Type', 'Event', 'Transaction Type', 'Order Type', 'Type'
      ])).toLowerCase();

      // Amounts
      const taxableNum = parseFloat(getVal(row, [
        'Taxable Value (Final Invoice Amount -Taxes)', 'Taxable Value', 'Taxable Amount', 'Net Amount', 'Sale Amount'
      ], 0)) || 0;

      const invoiceValNum = parseFloat(getVal(row, [
        'Buyer Invoice Amount', 'Final Invoice Amount (Price after discount+Shipping Charges)',
        'Final Invoice Amount', 'Invoice Amount', 'Total Amount', 'Gross Amount'
      ], 0)) || taxableNum;

      let type = 'sale';
      if (eventTypeRaw.includes('return') || eventTypeRaw.includes('refund') || eventTypeRaw.includes('debit') || taxableNum < 0) {
        type = 'return';
      } else if (eventTypeRaw.includes('cancel')) {
        type = 'cancellation';
      }

      const taxableRaw = Math.abs(taxableNum);
      const invoiceValueRaw = Math.abs(invoiceValNum);

      const buyerGstin = String(getVal(row, [
        'Business GST Number', 'Buyer GSTIN', 'Customer GSTIN', 'Buyer GST', 'Customer Tax ID'
      ])).trim().toUpperCase();

      // Ship From & Place of supply
      const shipFromRaw = getVal(row, [
        'Order Shipped From (State)', 'Warehouse State', 'Dispatch State', 'Ship From State', 'Seller State', 'Hub State'
      ]);
      const placeOfSupplyRaw = getVal(row, [
        "Customer's Delivery State", "Customer's Billing State", 'Customer State', 'Delivery State',
        'Buyer State', 'Place of Supply', 'Destination State'
      ]);

      const shipFromState = resolveStateCode(shipFromRaw) || sellerStateCode || '';
      const placeOfSupply = resolveStateCode(placeOfSupplyRaw) || shipFromState || '';

      if (!placeOfSupply) {
        warnings.push({
          type: 'WARNING',
          field: 'placeOfSupply',
          sourceRow: rowIndex,
          platform: 'flipkart',
          message: `Sheet ${sheetName} Row ${rowIndex}: Could not resolve Place of Supply for invoice ${invoiceNumber || orderId}`,
        });
      }

      // Tax rates & amounts
      let igstRate = parseFloat(getVal(row, ['IGST Rate', 'IGST %', 'Rate of IGST'], 0)) || 0;
      let cgstRate = parseFloat(getVal(row, ['CGST Rate', 'CGST %', 'Rate of CGST'], 0)) || 0;
      let sgstRate = parseFloat(getVal(row, [
        'SGST Rate (or UTGST as applicable)', 'SGST Rate', 'SGST %', 'Rate of SGST'
      ], 0)) || 0;
      
      let gstRate = igstRate > 0 ? igstRate : (cgstRate + sgstRate);
      if (gstRate === 0) {
        gstRate = parseFloat(getVal(row, ['GST Rate', 'Tax Rate', 'Rate'], 0)) || 0;
      }

      let igstRaw = Math.abs(parseFloat(getVal(row, ['IGST Amount', 'IGST'], 0)) || 0);
      let cgstRaw = Math.abs(parseFloat(getVal(row, ['CGST Amount', 'CGST'], 0)) || 0);
      let sgstRaw = Math.abs(parseFloat(getVal(row, [
        'SGST Amount (Or UTGST as applicable)', 'SGST Amount', 'SGST'
      ], 0)) || 0);
      const cessRaw = Math.abs(parseFloat(getVal(row, ['Luxury Cess Amount', 'Cess Amount', 'CESS', 'Cess'], 0)) || 0);

      // If taxes are not calculated in file, compute from rate & state logic
      if (igstRaw === 0 && cgstRaw === 0 && sgstRaw === 0 && gstRate > 0 && taxableRaw > 0) {
        const isInterState = shipFromState !== placeOfSupply;
        if (isInterState) {
          igstRaw = Number(((taxableRaw * gstRate) / 100).toFixed(2));
        } else {
          const halfRate = gstRate / 2;
          cgstRaw = Number(((taxableRaw * halfRate) / 100).toFixed(2));
          sgstRaw = Number(((taxableRaw * halfRate) / 100).toFixed(2));
        }
      }

      const hsn = String(getVal(row, ['HSN Code', 'HSN', 'SAC', 'HSN/SAC'])).trim();
      const description = String(getVal(row, [
        'Product Title/Description', 'Product Title', 'Title', 'Description', 'SKU'
      ])).trim();
      const quantity = Math.abs(parseInt(getVal(row, ['Item Quantity', 'Quantity', 'Qty'], 1), 10)) || 1;

      const platformGstin = String(getVal(row, [
        'ECO GSTIN', 'E-Commerce Operator GSTIN'
      ], MARKETPLACE_ETIN.FLIPKART[0])).trim().toUpperCase();

      orderLines.push({
        platform: 'flipkart',
        orderId,
        invoiceNumber: invoiceNumber || orderId,
        invoiceDate,
        type,
        buyerGstin: buyerGstin.length === 15 ? buyerGstin : '',
        shipFromState,
        placeOfSupply,
        hsn,
        description,
        quantity,
        uqc: 'OTH',
        taxableValuePaise: toPaise(taxableRaw),
        gstRate,
        igstPaise: toPaise(igstRaw),
        cgstPaise: toPaise(cgstRaw),
        sgstPaise: toPaise(sgstRaw),
        cessPaise: toPaise(cessRaw),
        invoiceValuePaise: toPaise(invoiceValueRaw),
        platformGstin,
        sourceRow: rowIndex,
      });
    }
  }

  return {
    platform: 'flipkart',
    rowCount: orderLines.length,
    orderLines,
    errors,
    warnings,
  };
}

